#
# USED FOR TESTING ONLY
#

# Queries to run on the parent account, and replicate to the child accounts
#
# These queries will only run if there is a 'nr-replicator-accountId' and 'nr-replicator-apiToken'
# secret in the namespace.
#
# Available variables to use, these get replaced before running the query:
# - $namespace: Will be replaced with the current namespace
queries:
  - SELECT average(cpuUsedCores) as 'cpu-cores-utilization', average(memoryUsedBytes) as 'memory-usage' FROM K8sContainerSample FACET podName, containerName WHERE namespace = '$namespace' SINCE 60 minutes ago LIMIT 1000
